<?php
// -----
// Part of the Bootstrap template, assigning colors based on those configured.
//
// BOOTSTRAP v3.8.0
//
// Starting with Bootstrap v3.5.2, any color-specifications defined in that and follow-on
// versions start out, on an upgrade, with a value of 'not-set' to give the site a chance
// to define those colors to be compatible with the site's color scheme.
//
// Converting to CSS variables, starting in Bootstrap v3.8.0.
//

// -----
// There are a couple of "mis-named" color-configuration settings (these are 'legacy'
// and won't be changed in the database).  For the purists amongst us, set definitions
// that are used below (as of v3.6.0) that make more sense.
//
$renamed_colors = [
    'ZCA_BUTTON_BACKGROUND_COLOR' => $tplSetting->ZCA_BUTTON_COLOR,
    'ZCA_BUTTON_BACKGROUND_COLOR_HOVER' => $tplSetting->ZCA_BUTTON_COLOR_HOVER,
    'ZCA_HEADER_TABS_BACKGROUND_COLOR' => $tplSetting->ZCA_HEADER_TABS_COLOR,
    'ZCA_HEADER_TABS_BACKGROUND_COLOR_HOVER' => $tplSetting->ZCA_HEADER_TABS_COLOR_HOVER,

    // -----
    // Ditto for some of the color-settings that affect *only* the hamburger-menu-icon used
    // on the mobile display.  Define aliases for use in the CSS-generating portion of this
    // script for clarity.
    //
    'ZCA_HEADER_NAVBAR_TOGGLER_COLOR' => $tplSetting->ZCA_HEADER_NAVBAR_BUTTON_TEXT_COLOR,
    'ZCA_HEADER_NAVBAR_TOGGLER_COLOR_HOVER' => $tplSetting->ZCA_HEADER_NAVBAR_BUTTON_TEXT_COLOR_HOVER,
    'ZCA_HEADER_NAVBAR_TOGGLER_BACKGROUND_COLOR' => $tplSetting->ZCA_HEADER_NAVBAR_BUTTON_COLOR,
    'ZCA_HEADER_NAVBAR_TOGGLER_BACKGROUND_COLOR_HOVER' => $tplSetting->ZCA_HEADER_NAVBAR_BUTTON_COLOR_HOVER,
    'ZCA_HEADER_NAVBAR_TOGGLER_BORDER_COLOR' => $tplSetting->ZCA_HEADER_NAVBAR_BUTTON_BORDER_COLOR,
    'ZCA_HEADER_NAVBAR_TOGGLER_BORDER_COLOR_HOVER' => $tplSetting->ZCA_HEADER_NAVBAR_BUTTON_BORDER_COLOR_HOVER,
];

$bootstrap_colors = [
    'ZCA_BODY_BACKGROUND_COLOR',
    'ZCA_BODY_TEXT_COLOR',
    'ZCA_BODY_BREADCRUMBS_BACKGROUND_COLOR',
    'ZCA_BODY_BREADCRUMBS_TEXT_COLOR',
    'ZCA_BODY_BREADCRUMBS_LINK_COLOR',
    'ZCA_BODY_BREADCRUMBS_LINK_COLOR_HOVER',
    'ZCA_BODY_PRODUCTS_BASE_COLOR',
    'ZCA_BODY_PRODUCTS_NORMAL_COLOR',
    'ZCA_BODY_PRODUCTS_SPECIAL_COLOR',
    'ZCA_BODY_PRODUCTS_DISCOUNT_COLOR',
    'ZCA_BODY_PRODUCTS_SALE_COLOR',
    'ZCA_BODY_PRODUCTS_FREE_COLOR',
    'ZCA_BODY_PLACEHOLDER',
    'ZCA_ALERT_INFO_COLOR',
    'ZCA_ALERT_INFO_BACKGROUND_COLOR',
    'ZCA_ALERT_INFO_BORDER_COLOR',
    'ZCA_BODY_RATING_STAR_BACKGROUND_COLOR',
    'ZCA_BODY_RATING_STAR_COLOR',
    'ZCA_BUTTON_TEXT_COLOR',
    'ZCA_BUTTON_TEXT_COLOR_HOVER',
    'ZCA_BUTTON_BACKGROUND_COLOR',
    'ZCA_BUTTON_BACKGROUND_COLOR_HOVER',
    'ZCA_BUTTON_BORDER_COLOR',
    'ZCA_BUTTON_BORDER_COLOR_HOVER',
    'ZCA_BUTTON_LINK_COLOR',
    'ZCA_BUTTON_LINK_COLOR_HOVER',
    'ZCA_BUTTON_PAGEINATION_TEXT_COLOR',
    'ZCA_BUTTON_PAGEINATION_TEXT_COLOR_HOVER',
    'ZCA_BUTTON_PAGEINATION_COLOR',
    'ZCA_BUTTON_PAGEINATION_COLOR_HOVER',
    'ZCA_BUTTON_PAGEINATION_BORDER_COLOR',
    'ZCA_BUTTON_PAGEINATION_BORDER_COLOR_HOVER',
    'ZCA_BUTTON_PAGEINATION_ACTIVE_TEXT_COLOR',
    'ZCA_BUTTON_PAGEINATION_ACTIVE_COLOR',
    'ZCA_HEADER_WRAPPER_BACKGROUND_COLOR',
    'ZCA_HEADER_TAGLINE_TEXT_COLOR',
    'ZCA_HEADER_NAV_BAR_BACKGROUND_COLOR',
    'ZCA_HEADER_NAVBAR_LINK_COLOR',
    'ZCA_HEADER_NAVBAR_LINK_COLOR_HOVER',
    'ZCA_HEADER_NAVBAR_LINK_BACKGROUND_COLOR_HOVER',
    'ZCA_HEADER_NAVBAR_TOGGLER_COLOR',
    'ZCA_HEADER_NAVBAR_TOGGLER_COLOR_HOVER',
    'ZCA_HEADER_NAVBAR_TOGGLER_BACKGROUND_COLOR',
    'ZCA_HEADER_NAVBAR_TOGGLER_BACKGROUND_COLOR_HOVER',
    'ZCA_HEADER_NAVBAR_TOGGLER_BORDER_COLOR',
    'ZCA_HEADER_NAVBAR_TOGGLER_BORDER_COLOR_HOVER',
    'ZCA_HEADER_NAVBAR_EXTRA_BUTTON_TEXT_COLOR',
    'ZCA_HEADER_NAVBAR_EXTRA_BUTTON_TEXT_COLOR_HOVER',
    'ZCA_HEADER_NAVBAR_EXTRA_BUTTON_BACKGROUND_COLOR',
    'ZCA_HEADER_NAVBAR_EXTRA_BUTTON_BACKGROUND_COLOR_HOVER',
    'ZCA_HEADER_NAVBAR_EXTRA_BUTTON_BORDER_COLOR',
    'ZCA_HEADER_NAVBAR_EXTRA_BUTTON_BORDER_COLOR_HOVER',
    'ZCA_HEADER_TABS_BACKGROUND_COLOR',
    'ZCA_HEADER_TABS_BACKGROUND_COLOR_HOVER',
    'ZCA_HEADER_TABS_TEXT_COLOR',
    'ZCA_HEADER_TABS_TEXT_COLOR_HOVER',
    'ZCA_HEADER_TABS_BORDER_COLOR',
    'ZCA_HEADER_TABS_BORDER_COLOR_HOVER',
    'ZCA_HEADER_TABS_ACTIVE_BACKGROUND_COLOR',
    'ZCA_HEADER_TABS_ACTIVE_BACKGROUND_COLOR_HOVER',
    'ZCA_HEADER_TABS_ACTIVE_COLOR',
    'ZCA_HEADER_TABS_ACTIVE_COLOR_HOVER',
    'ZCA_HEADER_TABS_ACTIVE_BORDER_COLOR',
    'ZCA_HEADER_TABS_ACTIVE_BORDER_COLOR_HOVER',
    'ZCA_HEADER_EZPAGE_BACKGROUND_COLOR',
    'ZCA_HEADER_EZPAGE_BACKGROUND_COLOR_HOVER',
    'ZCA_HEADER_EZPAGE_LINK_COLOR',
    'ZCA_HEADER_EZPAGE_LINK_COLOR_HOVER',
    'ZCA_FOOTER_WRAPPER_BACKGROUND_COLOR',
    'ZCA_FOOTER_WRAPPER_TEXT_COLOR',
    'ZCA_FOOTER_EZPAGE_BACKGROUND_COLOR',
    'ZCA_FOOTER_EZPAGE_BACKGROUND_COLOR_HOVER',
    'ZCA_FOOTER_EZPAGE_LINK_COLOR',
    'ZCA_FOOTER_EZPAGE_LINK_COLOR_HOVER',
    'ZCA_SIDEBOX_BACKGROUND_COLOR',
    'ZCA_SIDEBOX_TEXT_COLOR',
    'ZCA_SIDEBOX_LINK_BACKGROUND_COLOR',
    'ZCA_SIDEBOX_LINK_BACKGROUND_COLOR_HOVER',
    'ZCA_SIDEBOX_LINK_COLOR',
    'ZCA_SIDEBOX_LINK_COLOR_HOVER',
    'ZCA_SIDEBOX_CARD_BACKGROUND_COLOR',
    'ZCA_SIDEBOX_CARD_BACKGROUND_COLOR_HOVER',
    'ZCA_SIDEBOX_HEADER_BACKGROUND_COLOR',
    'ZCA_SIDEBOX_HEADER_TEXT_COLOR',
    'ZCA_SIDEBOX_HEADER_LINK_COLOR',
    'ZCA_SIDEBOX_HEADER_LINK_COLOR_HOVER',
    'ZCA_SIDEBOX_COUNTS_BACKGROUND_COLOR',
    'ZCA_SIDEBOX_COUNTS_COLOR',
    'ZCA_CENTERBOX_BACKGROUND_COLOR',
    'ZCA_CENTERBOX_TEXT_COLOR',
    'ZCA_CENTERBOX_CARD_BACKGROUND_COLOR',
    'ZCA_CENTERBOX_CARD_BACKGROUND_COLOR_HOVER',
    'ZCA_CENTERBOX_HEADER_BACKGROUND_COLOR',
    'ZCA_CENTERBOX_HEADER_TEXT_COLOR',
    'ZCA_ADD_TO_CART_BACKGROUND_COLOR',
    'ZCA_ADD_TO_CART_TEXT_COLOR',
    'ZCA_ADD_TO_CART_BORDER_COLOR',
    'ZCA_BUTTON_IN_CART_BACKGROUND_COLOR',
    'ZCA_BUTTON_IN_CART_BACKGROUND_COLOR_HOVER',
    'ZCA_BUTTON_IN_CART_TEXT_COLOR',
    'ZCA_BUTTON_IN_CART_TEXT_COLOR_HOVER',
    'ZCA_BUTTON_ADD_SELECTED_BACKGROUND_COLOR',
    'ZCA_BUTTON_ADD_SELECTED_BACKGROUND_COLOR_HOVER',
    'ZCA_BUTTON_ADD_SELECTED_TEXT_COLOR',
    'ZCA_BUTTON_ADD_SELECTED_TEXT_COLOR_HOVER',
    'ZCA_CHECKOUT_PROGRESS_BAR_BACKGROUND_COLOR',
    'ZCA_CHECKOUT_CONTINUE_BACKGROUND_COLOR',
    'ZCA_CHECKOUT_CONTINUE_BACKGROUND_COLOR_HOVER',
    'ZCA_CHECKOUT_CONTINUE_COLOR',
    'ZCA_CHECKOUT_CONTINUE_COLOR_HOVER',
    'ZCA_CHECKOUT_CONTINUE_BORDER_COLOR',
    'ZCA_CHECKOUT_CONTINUE_BORDER_COLOR_HOVER',
    'ZCA_CHECKOUT_CONFIRM_BACKGROUND_COLOR',
    'ZCA_CHECKOUT_CONFIRM_BACKGROUND_COLOR_HOVER',
    'ZCA_CHECKOUT_CONFIRM_COLOR',
    'ZCA_CHECKOUT_CONFIRM_COLOR_HOVER',
    'ZCA_CHECKOUT_CONFIRM_BORDER_COLOR',
    'ZCA_CHECKOUT_CONFIRM_BORDER_COLOR_HOVER',
    'ZCA_SOLD_OUT_BACKGROUND_COLOR',
    'ZCA_SOLD_OUT_COLOR',
    'ZCA_SOLD_OUT_BORDER_COLOR',
    'ZCA_CAROUSEL_PREV_NEXT_COLOR',
    'ZCA_CAROUSEL_PREV_NEXT_COLOR_HOVER',
    'ZCA_CAROUSEL_BANNER_INDICATORS_BACKGROUND_COLOR',
    'ZCA_PRIMARY_ADDRESS_ADDRESS_BACKGROUND_COLOR',
    'ZCA_PRIMARY_ADDRESS_ADDRESS_COLOR',
    'ZCA_PRIMARY_ADDRESS_CARD_HEADER_BACKGROUND_COLOR',
    'ZCA_PRIMARY_ADDRESS_CARD_HEADER_COLOR',
    'ZCA_PRIMARY_ADDRESS_CARD_BORDER_COLOR',
];
?>
<style id="bs4-color-vars">
:root {
<?php
foreach ($bootstrap_colors as $color_key) {
    $color_val = $tplSetting->$color_key ?? $renamed_colors[$color_key] ?? 'inherit';
    if ($color_val === 'not-set') {
        $color_val = 'inherit';
    }
    $color_key = strtolower($color_key);
?>
    --<?= $color_key ?>: <?= $color_val ?>;
<?php
}
unset($renamed_colors, $bootstrap_colors, $color_key, $color_val);
?>
}
</style>
